 trigger:
   - main

 pool:
   vmImage: 'ubuntu-latest'
      
 variables:
   CS_REGISTRY: "registry.crowdstrike.com"
   CS_IMAGE_NAME: "crowdstrike.com/fcs/eu-1/release/cs-fcs"
   CS_USERNAME: "fh-39AECBE16A5D4284B1E412F3AC267D18"
   CS_IMAGE_TAG: "2.1.0"
   FALCON_API_URL: "https://api.eu-1.crowdstrike.com"
   FALCON_REGION: "eu-1"
   PROJECT_PATH: "$(Build.Repository.LocalPath)"
 
 steps:
  # Obtenir le token API et le password du registre
  - script: |
      set -e
      echo "Getting Falcon API Access Token..."      
      export FALCON_ACCESS_TOKEN=$(curl --silent --request POST \
        --header "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "client_id=${FALCON_CLIENT_ID}" \
        --data-urlencode "client_secret=${FALCON_CLIENT_SECRET}" \
        --url "${FALCON_API_URL}/oauth2/token" | jq -r '.access_token')

      if [ -z "$FALCON_ACCESS_TOKEN" ] || [ "$FALCON_ACCESS_TOKEN" = "null" ]; then
        echo "Failed to retrieve Falcon API access token"
        echo "$FALCON_ACCESS_TOKEN"
        exit 1
      fi

      echo "Getting CrowdStrike registry password..."
      export CS_PASSWORD=$(curl --silent --request GET \
        --header "Authorization: Bearer ${FALCON_ACCESS_TOKEN}" \
        --url "${FALCON_API_URL}/iac/entities/image-registry-credentials/v1" | jq -r '.resources.resources.token')

      if [ -z "$CS_PASSWORD" ] || [ "$CS_PASSWORD" = "null" ]; then
        echo "Failed to retrieve CrowdStrike registry password"
        exit 1
      fi
      # Pour propager la variable à l’étape suivante
      echo "##vso[task.setvariable variable=CS_PASSWORD]$CS_PASSWORD"
    displayName: 'Get Falcon API Token and Registry Password'
  # Vérification des variables d'environnement requises
  - script: |
      set +x
      scan_status=0
      if [[ -z "$CS_USERNAME" || -z "$CS_PASSWORD" || -z "$CS_REGISTRY" || -z "$CS_IMAGE_NAME" || -z "$CS_IMAGE_TAG" || -z "$FALCON_CLIENT_ID" || -z "$FALCON_CLIENT_SECRET" || -z "$FALCON_REGION" || -z "$PROJECT_PATH" ]]; then
        echo "Error: required environment variables/params are not set"
        exit 1
      fi

      echo "Logging in to crowdstrike registry with username: $CS_USERNAME"
      echo "$CS_PASSWORD" | docker login "$CS_REGISTRY" --username "$CS_USERNAME" --password-stdin

      if [ $? -eq 0 ]; then
        echo "Docker login successful"
        echo "Pulling fcs container target from crowdstrike"
        docker pull "$CS_IMAGE_NAME":"$CS_IMAGE_TAG"
        if [ $? -eq 0 ]; then
          echo "fcs docker container image pulled successfully"
          echo "=============== FCS IaC Scan Starts ==============="
          docker run --network=host --rm "$CS_IMAGE_NAME":"$CS_IMAGE_TAG" --client-id "$FALCON_CLIENT_ID" --client-secret "$FALCON_CLIENT_SECRET" --falcon-region "$FALCON_REGION" scan iac --path "$PROJECT_PATH" --fail-on "critical=10,high=70,medium=50,informational=10"
          scan_status=$?
          echo "=============== FCS IaC Scan Ends ==============="
          echo "fcs-iac-scan-status: ${scan_status}"
          echo $scan_status > fcs_scan_status.txt
        else
          echo "Error: failed to pull fcs docker image from crowdstrike"
          exit 2
        fi
      else
        echo "Error: docker login failed"
        exit 3
      fi
    displayName: 'Run FCS IaC scan in Docker'

  # Gestion des codes de sortie et marquage du build
  - script: |
      scan_status=$(cat fcs_scan_status.txt)
      echo "Returned scan status: $scan_status"
      if [ "$scan_status" -eq 40 ]; then
        echo "Scan succeeded & vulnerabilities count are ABOVE the '--fail-on' threshold; Pipeline will be marked as SucceededWithIssues."
        echo "##vso[task.complete result=SucceededWithIssues;]Scan found vulnerabilities above threshold"
      elif [ "$scan_status" -eq 0 ]; then
        echo "Scan succeeded & vulnerabilities count are BELOW the '--fail-on' threshold; Pipeline will be marked as Success."
      else
        echo "Unexpected scan exit code: $scan_status"
        echo "##vso[task.complete result=Failed;]Unexpected scan exit code: $scan_status"
        exit 1
      fi
    displayName: 'Evaluate scan status and mark build'

  # Affichage final (toujours exécuté)
  - script: |
      echo "FCS IaC Scan Execution complete.."
    displayName: 'Always - Scan Complete'


#  Wiz & Palo variables
#  variables:
#    SCAN_PATH: "$(Build.Repository.LocalPath)"
#    CORTEX_API_URL: "https://api-pov-2025-gk4pa.xdr.fa.paloaltonetworks.com"
#    MIN_LOG_LEVEL: "DEBUG"



#  Wiz CLI
# steps:
#   - script: |
#       echo "##[command]Obtaining WizCLI from the inter-webs..."
#       sudo curl -o /usr/bin/wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64
#       echo "##[command]Making WizCLI executable"
#       sudo chmod +x /usr/bin/wizcli
#       /usr/bin/./wizcli auth --id $(WIZ_CLIENT_ID2) --secret $(WIZ_CLIENT_SECRET2)
#       /usr/bin/./wizcli iac scan --path "$SCAN_PATH"
#       /usr/bin/./wizcli dir scan --path "$SCAN_PATH"



#  Cortex CLI
#  steps:
#   - checkout: self
#     clean: true
#   - task: NodeTool@0
#     displayName: "Use Node.js 22.x"
#     inputs:
#       versionSpec: "22.x"
#   - bash: |
#       set -euo pipefail
#       sudo apt-get update
#       sudo apt-get install -y --no-install-recommends jq ca-certificates curl
#       BASE="${CORTEX_API_URL%/}"
#       URL="$BASE/public_api/v1/unified-cli/releases/download-link?os=linux&architecture=amd64"
#       set +x
#       CRTX_URL=$(curl -fsSL "$URL" \
#         -H "x-xdr-auth-id: ${CORTEX_API_KEY_ID2}" \
#         -H "Authorization: ${CORTEX_API_KEY2}" | jq -r '.signed_url')
#       set -x
#       curl -fsSL -o cortexcli "$CRTX_URL"
#       sudo chmod +x cortexcli
#       cat /tmp/cortexcli-2417593210.log
#     displayName: "Download cortexcli (amd64)"
#     env:
#       CORTEX_API_URL: $(CORTEX_API_URL)
#       CORTEX_API_KEY_ID2: $(CORTEX_API_KEY_ID2)
#       CORTEX_API_KEY2: $(CORTEX_API_KEY2)
#   - bash: |
#       set -euo pipefail
#       ./cortexcli \
#         --api-base-url "${CORTEX_API_URL}" \
#         --api-key "${CORTEX_API_KEY2}" \
#         --api-key-id "${CORTEX_API_KEY_ID2}" \
#         code scan \
#         --directory "$(Build.SourcesDirectory)" \
#         --repo-id "$(Build.Repository.Name)" \
#         --branch "$(Build.SourceBranchName)" \
#         --source "CORTEX_CLI" \
#         --create-repo-if-missing
#       cat /tmp/cortexcli-2417593210.log
#     displayName: "Cortex CLI Code Scan"
#     env:
#       CORTEX_API_URL: $(CORTEX_API_URL)
#       CORTEX_API_KEY_ID2: $(CORTEX_API_KEY_ID2)
#       CORTEX_API_KEY2: $(CORTEX_API_KEY2)
#       MIN_LOG_LEVEL: $(MIN_LOG_LEVEL)